let myName = 'Makayla';
document.write(myName);
myName = 'Molina';
document.write(myName);
let simpleAddition = 2 + 2;
document.write(simpleAddition);
let size = 100;
let doubleSize = size * 2;
let minSize = (doubleSize * 2) - (size / 2);
document.write(doubleSize);
let favoriteFood = 'Spaghetti';
document.write(favoriteFood);